# Generated by Django 6.0 on 2025-12-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('EVALUATING_RFP', 'Evaluating RFP'), ('WRITING_RFP', 'Writing RFP'), ('BOOKED', 'Booked (unstarted)'), ('LOST', 'Lost'), ('NOT_AWARDED', 'Not awarded'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='EVALUATING_RFP', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client.client')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.projecttype')),
            ],
            options={
                'ordering': ['client__name', 'name'],
            },
        ),
    ]
