# Generated by Django 6.0 on 2025-12-31 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of task.')),
                ('instructions', models.TextField(help_text='Specific instructions for completion of task. If using this field, consider creating child subtasks.')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('hours_estimate', models.FloatField(default=0, help_text='Estimated hours to complete')),
                ('dependent_hours', models.FloatField(default=0)),
                ('buffer_before', models.PositiveSmallIntegerField(default=0, help_text='Buffer days between scheduled prerequisites and start of task')),
                ('buffer_after', models.PositiveSmallIntegerField(default=0, help_text='Buffer days between completion of task and scheduling of dependencies')),
                ('schedule_datetime', models.DateTimeField(default=None, null=True)),
                ('auto_schedule', models.BooleanField(default=True)),
                ('due_date', models.DateField(default=None, null=True)),
                ('risk_hours', models.FloatField(default=0, help_text='Number of hours estimated over due date for task to be completed.')),
                ('auto_assign', models.BooleanField(default=True, help_text='Whether scheduler should automatically assign this task')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to complete this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='task.task')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='task.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='task.task')),
                ('user', models.ForeignKey(help_text='User who performed the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
